version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get install wkhtmltopdf

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - run: yarn run validate

      - run: yarn run analyze

      - run: yarn run build